# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = IMAGEPS
DESTDIR = ../x64/Release
CONFIG += debug
LIBS += -L"$(SolutionDir)3thirdPar/opencv/lib" \
    -lopencv_world480
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(../../../IMAGEPS.pri)
